language: node_js
node_js:
  - "node"
cache:
  - npm
  - node_modules
script: echo "Running tests against $(node -v) ..."
script: npm run gulp-build
jobs:
  include:
    - script: echo "Running unit tests (1)"
    - script: echo "Running unit tests (2)"
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      script: gem install travis
      script: travis encrypt secure="heyther" --add      
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: f66878606087a4111195b364845a2ae7ec3bbe38
        keep_history: true
        on:
          branch: master