language: node_js
node_js:
  - "node"
cache:
  - npm
  - node_modules
script: echo "Running tests against $(node -v) ..."
script: npm run gulp-build
jobs:
  include:
    - script: echo "Running unit tests (1)"
    - script: echo "Running unit tests (2)"
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."      
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: dist
        github_token: $github_token
        keep_history: true
        target_branch: gh-pages
        on:
          branch: master