language: node_js
node_js:
  - "node"
script: echo "Running tests against $(node -v) ..."
script: npm run gulp-build
jobs:
  include:
    - script: echo "Running unit tests (1)"
    - script: echo "Running unit tests (2)"
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: 5dd7daa809cab3f1ec015073e26eb4daac8786b5
        keep_history: true
        on:
          branch: master